### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by ChrisJReeves** [jkroso/equals#6]
I'm installing pouchdb-express on windows7 and I get the following error on equals/type:

C:\test\Node App2>npm install equals
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/jkroso/type) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://githu
b.com/jkroso/type) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.
com:jkroso/type) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.
com:jkroso/type) undefined
npm ERR! git clone git@github.com:jkroso/type undefined
npm ERR! git clone git@github.com:jkroso/type undefined
npm ERR! notarget No compatible version found: type@'jkroso/type#1.1.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1","0.0.2","0.0.3"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\test\\Node App2\\\\node.exe" "C:\\test\\Node App2\\node_mo
dules\\npm\\bin\\npm-cli.js" "install" "equals"
npm ERR! cwd C:\test\Node App2
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ETARGET
npm ERR! not ok code 0

Regards

Chris

**Comment by BrianRossmajer** [comment]
I had the same problem because git was not installed in the target environment, so npm could not use github specs in the version field.

I fixed it with npm shrinkwrap, but the equivalent fix would be to replace the github spec ("jkroso/type") with a github tarball url, like "https://github.com/jkroso/type/tarball/da1aa82f8673cabd6a3d4b6ca1961161aef2cf95"

Alternately, you could publish `jkroso/type` to npmjs and change the version string to something like "^1.1.0".

Hope that helps!

**Comment by jkroso** [comment]
Great I'm glad npm's error reporting made that so easy for everyone. Not.

I think I will just publish that dep to npm as jkroso-type
